# Generated by Django 4.2.13 on 2024-05-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
